site_name: Appclusive Documentation

pages:
- Introduction: Introduction.md
- About: about.md
- 'What is new?': WhatsNew.md
- Clients:
    - PowerShell: Clients/PowerShell.md
- Processes:
    - OrderProcess: Processes/OrderProcess.md
- Endpoints:
    - Api: Endpoints/Api.md
    - Managers: Endpoints/Managers.md
    - Catalogue:
        - Blueprint: Endpoints/Core/Catalogue/Blueprint.md
        - Catalogue: Endpoints/Core/Catalogue/Catalogue.md
- Examples:
    - Examples: Examples/Examples.md
    - Modelling: Examples/Modelling.md
- Installation:
    - Installation: Installation/Installation.md
    - Onboarding: Installation/Onboarding.md
    - Setup: Installation/Setup.md
    - Troubleshooting: Installation/Troubleshooting.md
- Development:
    - BlueprintEngine: Development/BlueprintEngine.md
    - ODataEndpoints: Development/ODataEndpoints.md
    - Workflows: Development/Workflows.md

