site_name: Appclusive Documentation

pages:
- Introduction: introduction.md
- About: about.md
- 'What is new?': WhatsNew.md
- Clients:
    - PowerShell: Clients/PowerShell.md
- Processes:
    - OrderProcess: OrderProcess.md
- Endpoints:
    - Api: Api.md
    - Managers: Managers.md
    - Catalogue:
        - Blueprint: Blueprint.md
        - Catalogue: Catalogue.md
- Examples:
    - Examples: Examples.md
    - Modelling: Modelling.md
- Installation:
    - Installation: Installation.md
    - Onboarding: Onboarding.md
    - Setup: Setup.md
    - Troubleshooting: Troubleshooting.md
- Development:
    - BlueprintEngine: BlueprintEngine.md
    - ODataEndpoints: ODataEndpoints.md
    - Workflows: Workflows.md

