site_name: Appclusive Documentation

pages:
- Home: index.md
- Introduction: Introduction.md
- 'What''s new?': ReleaseNotes.md
- Clients:
    - Intro: Clients/index.md
    - PowerShell: Clients/PowerShell.md
    - 'C# .NET': Clients/CSharpDotNet.md
- Processes: 
    - OrderProcess: Processes/OrderProcess.md
- Endpoints:
    - Api: Endpoints/Api.md
    - Managers: Endpoints/Managers.md
    - Catalogue:
        - Blueprint: Endpoints/Core/Catalogue/Blueprint.md
        - Catalogue: Endpoints/Core/Catalogue/Catalogue.md
- Examples:
    - Intro: Examples/index.md
    - Modelling: Examples/Modelling.md
- Installation:
    - Installation: Installation/Installation.md
    - Onboarding: Installation/Onboarding.md
    - Setup: Installation/Setup.md
    - Troubleshooting: Installation/Troubleshooting.md
- Development:
    - BlueprintEngine: Development/BlueprintEngine.md
    - ODataEndpoints: Development/ODataEndpoints.md
    - Workflows: Development/Workflows.md


markdown_extensions:
    - toc:
        permalink: 
    - admonition:

