site_name: Appclusive Documentation

pages:
- 'Introduction': 'index.md'
- 'About': 'about.md'
- 'What is new?': 'WhatsNew.md'
- Clients: 'Clients/!index.md'
    - PowerShell: 'Clients/PowerShell.md'
